### ISSUE TITLE
스켈레톤 작성

### ISSUE THREAD

**Issue by nerdrun** [nerdrun/calculator#1]
프로젝트를 시작하기 위한 스켈레톤을 작성합니다.

- main() 함수

**Comment by nerdrun** [comment]
사칙연산을 담당하는 각각의 함수를 작성하는 것이 좋겠습니다.
예를 들면 'add(int a, int b)', 'sub(int a, int b)' 등등

**Comment by Jny** [comment]
결과 값 출력도 있음 좋겟네요

**Comment by nerdrun** [comment]
알겠습니다!

**Comment by withgod072** [comment]
언제까지 코드 구현이 완료가 되는가요?

**Comment by nerdrun** [comment]
마일스톤 계획에서 날짜는 오늘까지입니다~

**Comment by nerdrun** [comment]
@withgod072 오늘까지입니다.
